### ISSUE TITLE
core.js:1449 ERROR TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by ohabash** [thisissoon/angular-inviewport#20]
console error (chrome)
`core.js:1449 ERROR TypeError: Object(...) is not a function`
![screen shot 2018-06-06 at 12 15 43 pm](https://user-images.githubusercontent.com/15847500/41054319-ab7ca312-6983-11e8-8b05-bb7457550ffe.png)

## at eval (`thisissoon-angular-inviewport.js:266`)
```
merge(fromEvent((_this.windowRef), eventWindowResize), fromEvent((_this.windowRef), eventWindowScroll))
```

maybe it has something to do with? See my `app.module.ts`.. I just guessed how to do get the ref by copying ur example code
```
import { InViewportModule, WindowRef } from '@thisissoon/angular-inviewport';

const providers = [
  { provide: WindowRef, useValue: window }
];
```

**Comment by edoparearyee** [comment]
Hi @ohabash I think the error you might be having is due to your `window`  object not containing `addEventListener` and `removeEventListener` methods which is strange? 

What version's of angular and rxjs are you using? Also are you doing any server side rendering?

**Comment by torresdaniel11** [comment]
i have the same error

**Comment by edoparearyee** [comment]
@ohabash @torresdaniel11 can you try updating to rxjs 6 and let me know if this resolves the issue

**Comment by jonathanstokes** [comment]
I'm getting this too.  Debugging a bit, there's an deeper Error happening:

    TypeError: Object(...) is not a function
        at eval (webpack-internal:///./node_modules/@thisissoon/angular-inviewport/esm5/thisissoon-angular-inviewport.js:281:120)
        at ZoneDelegate.invoke (webpack-internal:///./node_modules/zone.js/dist/zone.js:388:26)
        at Zone.run (webpack-internal:///./node_modules/zone.js/dist/zone.js:138:43)
        at NgZone.runOutsideAngular (webpack-internal:///./node_modules/@angular/core/esm5/core.js:4913:69)
        at InViewportDirective.ngAfterViewInit (webpack-internal:///./node_modules/@thisissoon/angular-inviewport/esm5/thisissoon-angular-inviewport.js:280:21)
        at callProviderLifecycles (webpack-internal:///./node_modules/@angular/core/esm5/core.js:12922:18)
        at callElementProvidersLifecycles (webpack-internal:///./node_modules/@angular/core/esm5/core.js:12889:13)
        at callLifecycleHooksChildrenFirst (webpack-internal:///./node_modules/@angular/core/esm5/core.js:12872:29)
        at checkAndUpdateView (webpack-internal:///./node_modules/@angular/core/esm5/core.js:14027:5)
        at callViewAction (webpack-internal:///./node_modules/@angular/core/esm5/core.js:14369:21)"

**Comment by jonathanstokes** [comment]
I'm hitting this too, with rxjs `5.5.2`.  When I try to make the same imports as `thisissoon-angular-inviewport.js`, it gives me:

    error TS2305: Module '".../node_modules/rxjs/Rx"' has no exported member 'fromEvent'.
    error TS2305: Module '".../node_modules/rxjs/Rx"' has no exported member 'merge'.

I'd love to use this library, but I don't think I can upgrade `rxjs` without upgrading Angular, which I can't afford to do right now.

**Comment by edoparearyee** [comment]
Hi @jonathanstokes @burzum619 @ohabash @torresdaniel11  and anyone else who is experiencing this issue please see the below which hopefully resolves the issue for everyone here:

## Cause
I believe this issue is just a case of a mismatch in versioning of `@angular/core`, `rxjs` and `@thisissoon/angular-inviewport`

## How to test
If you run `npm install` and get dependency warning related to `@thisissoon/angular-inviewport` it means that the versions of  `@angular/core`, `rxjs` and `@thisissoon/angular-inviewport` are not compatible with each other.

## Solutions
### Angular v5 users
either:
 * Run `npm i @thisissoon/angular-inviewport@2.2.0`. This is the last version tested against Angular v5
* Update to Angular v6 and it's dependencies.

### Rx.js v5 users
either: 
* Follow the above solution for Angular 5
* Run `npm i rxjs@6.2.2 rxjs-compat@6.2.2`. This will install the latest `rxjs` version but also the backwards compatible api to avoid breaking changes

**Comment by JDQN** [comment]
core.js:4442 ERROR TypeError: Cannot read property 'trim' of undefined
    at Week.formatDateRange (ej2-schedule.es2015.js:18754)
    at Week.getDateRangeText (ej2-schedule.es2015.js:18725)
    at Render.updateHeader (ej2-schedule.es2015.js:12025)
    at Render.initializeLayout (ej2-schedule.es2015.js:12004)
    at Render.render (ej2-schedule.es2015.js:11924)
    at ScheduleComponent.initializeView (ej2-schedule.es2015.js:14339)
    at ScheduleComponent.renderElements (ej2-schedule.es2015.js:14160)
    at ScheduleComponent.initializeResources (ej2-schedule.es2015.js:14142)
    at ScheduleComponent.render (ej2-schedule.es2015.js:14072)
    at ScheduleComponent.appendTo (ej2-base.es2015.js:6935)
defaultErrorLogger @ core.js:4442
client:52 

![Captura de Pantalla 2021-04-12 a la(s) 06 04 34 p  m](https://user-images.githubusercontent.com/74111185/114473294-966e5400-9bb9-11eb-9b0f-a6d7248517b9.png)

**Comment by JDQN** [comment]
Buenas tardes, saben como podría solucionar este error mi calendar se queda cargando cuando cambio el idioma a español lo estoy implementando con syncfusion gracias
